# Generated by Django 5.2.8 on 2025-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='peso',
            field=models.IntegerField(default=0, help_text='Peso do Pokémon(hectogramas)'),
        ),
    ]
